#! /usr/bin/env ruby
raise ArgumentError, 'Must provide day number as argument' unless ARGV[0]
DAY = ARGV[0].rjust(2, '0')
YEAR = ARGV[1] || '2020'

# Leave this in case I choose to add another language later
languages = [
  { name: 'Ruby', extension: '.rb'}
]


[1, 2].each do |part|
  languages.each do |language|
    file = "#{YEAR}/day#{DAY}/#{part}#{language[:extension]}"
    lines = File.read(file).split("\n")
    output = lines.count > 1 ? `#{file}` : "Not completed"
    puts "#{language[:name].ljust(6, ' ')} part #{part}: #{output}"
  end
end
