#! /usr/bin/env ruby
DAY = ARGV[0]? ARGV[0].rjust(2, '0') : Time.now.day
YEAR = ARGV[1] || Time.now.year

# Leave this in case I choose to add another language later
languages = [
  { name: 'Ruby', extension: '.rb'}
]


[1, 2].each do |part|
  languages.each do |language|
    file = "#{YEAR}/day#{DAY}/#{part}#{language[:extension]}"
    lines = File.read(file).split("\n")
    before = Time.now
    output = `#{file}`
    output = "Not completed" if output.empty?
    after = Time.now
    elapsed = (after - before) * 1000.0
    puts "#{language[:name].ljust(6, ' ')} part #{part} took #{elapsed}ms:\n#{output}"
    puts if part == 1
  end
end
